volumes:
  mysql:
    driver: local

services:
    db:
        image: mysql:8.0
        environment:
          TZ: "Asia/Tokyo"
          MYSQL_RANDOM_ROOT_PASSWORD: "yes"
          MYSQL_DATABASE: "app"
          MYSQL_USER: "app"
          MYSQL_PASSWORD: "secret"
        ports:
            - "3306:3306"
        volumes:
            - mysql:/var/lib/mysql

    php:
        build: docker/php
        environment:
            TZ: Asia/Tokyo
        ports:
            - "9000:9000"
        volumes:
            - .:/var/www/html
            - ./docker/php/config/extra.ini:/usr/local/etc/php/conf.d/extra.ini

    nginx:
        image: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./storage/logs:/var/log/nginx
            - ./docker/nginx/sites-enabled:/etc/nginx/conf.d
            - .:/var/www/html

    redis:
        image: redis:6
        ports:
            - "6379:6379"
